apiVersion: v1
kind: Service
metadata:
  name: ecs-external-service
  namespace: sock-shop
spec:
  type: ExternalName
  externalName: ecs-internal.thecloudgarage.com
  ports:
  - port: 9020
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecs-external-service-ingress
  namespace: sock-shop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0" #We had to do this else there is a 413 error when backups are sent via PUT request indicating the size is too large
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - ecs-kubedb-backup.thecloudgarage.com
    secretName: thecloudgarage-tls
  rules:
  - host: ecs-kubedb-backup.thecloudgarage.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ecs-external-service
            port:
              number: 9020
