# DO NOT CHANGE DATASOURCE NAME, AS IT IS SET AUTOMATICALLY VIA THE SCRIPT
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-restored-pv-claim-powerflex
  namespace: demo
  labels:
    name: mysql-restored-pv-claim-powerflex
    csi: csi-vxflexos.dellemc.com
spec:
  storageClassName: powerflex-sc
  dataSource:
    name: volumeSnapshotName
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
