apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: mysql-snapshot-powerflex-datetime
  labels:
    name: mysql-snapshot-powerflex-datetime
spec:
  volumeSnapshotClassName: vxflexos-snapclass
  source:
    persistentVolumeClaimName: mysql-pv-claim
