# Please change the name, region, vpc, subnet, instance type and other specs
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-apex-block-test-1
  region: eu-west-1
  version: "1.29"
vpc:
  publicAccessCIDRs: ["0.0.0.0/0"]
  id: "vpc-00bc8b021dafb7a92"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.26.0.0/22"       # (optional, must match CIDR used by the given VPC)
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      subnet1:
        id: "subnet-05b6a79635031102c"
        cidr: "172.26.2.0/26" # (optional, must match CIDR used by the given subnet)

      subnet2:
        id: "subnet-029718643080a4b86"
        cidr: "172.26.2.64/26"  # (optional, must match CIDR used by the given subnet)

      subnet3:
        id: "subnet-01c68677ddab29f0c"
        cidr: "172.26.2.128/26"  # (optional, must match CIDR used by the given subnet)
