#DONT CHANGE THE NAMESPACES FROM DEFAULT TO SOMETHING ELSE., SOMETHING WEIRD GOES ON!!!
#WE ARE STILL ABLE TO INJECT SECRETS IN TO DIFFERENT NAMESPACES VIA VAULTSTATICSECRETS CRD
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: default
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
